# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import jarvis_pb2 as jarvis__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jarvis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JarvisServiceStub(object):
    """Main JARVIS service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMessage = channel.unary_unary(
                '/jarvis.JarvisService/ProcessMessage',
                request_serializer=jarvis__pb2.MessageRequest.SerializeToString,
                response_deserializer=jarvis__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ExecuteAgent = channel.unary_unary(
                '/jarvis.JarvisService/ExecuteAgent',
                request_serializer=jarvis__pb2.AgentRequest.SerializeToString,
                response_deserializer=jarvis__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.StoreMemory = channel.unary_unary(
                '/jarvis.JarvisService/StoreMemory',
                request_serializer=jarvis__pb2.MemoryRequest.SerializeToString,
                response_deserializer=jarvis__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.RetrieveMemory = channel.unary_unary(
                '/jarvis.JarvisService/RetrieveMemory',
                request_serializer=jarvis__pb2.MemoryQuery.SerializeToString,
                response_deserializer=jarvis__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/jarvis.JarvisService/HealthCheck',
                request_serializer=jarvis__pb2.HealthRequest.SerializeToString,
                response_deserializer=jarvis__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/jarvis.JarvisService/StreamEvents',
                request_serializer=jarvis__pb2.EventStreamRequest.SerializeToString,
                response_deserializer=jarvis__pb2.Event.FromString,
                _registered_method=True)


class JarvisServiceServicer(object):
    """Main JARVIS service
    """

    def ProcessMessage(self, request, context):
        """Process incoming WhatsApp message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAgent(self, request, context):
        """Execute agent task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreMemory(self, request, context):
        """Memory operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Stream events (for real-time updates)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JarvisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMessage,
                    request_deserializer=jarvis__pb2.MessageRequest.FromString,
                    response_serializer=jarvis__pb2.MessageResponse.SerializeToString,
            ),
            'ExecuteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAgent,
                    request_deserializer=jarvis__pb2.AgentRequest.FromString,
                    response_serializer=jarvis__pb2.AgentResponse.SerializeToString,
            ),
            'StoreMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMemory,
                    request_deserializer=jarvis__pb2.MemoryRequest.FromString,
                    response_serializer=jarvis__pb2.MemoryResponse.SerializeToString,
            ),
            'RetrieveMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveMemory,
                    request_deserializer=jarvis__pb2.MemoryQuery.FromString,
                    response_serializer=jarvis__pb2.MemoryResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=jarvis__pb2.HealthRequest.FromString,
                    response_serializer=jarvis__pb2.HealthResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=jarvis__pb2.EventStreamRequest.FromString,
                    response_serializer=jarvis__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jarvis.JarvisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jarvis.JarvisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JarvisService(object):
    """Main JARVIS service
    """

    @staticmethod
    def ProcessMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jarvis.JarvisService/ProcessMessage',
            jarvis__pb2.MessageRequest.SerializeToString,
            jarvis__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jarvis.JarvisService/ExecuteAgent',
            jarvis__pb2.AgentRequest.SerializeToString,
            jarvis__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jarvis.JarvisService/StoreMemory',
            jarvis__pb2.MemoryRequest.SerializeToString,
            jarvis__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jarvis.JarvisService/RetrieveMemory',
            jarvis__pb2.MemoryQuery.SerializeToString,
            jarvis__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jarvis.JarvisService/HealthCheck',
            jarvis__pb2.HealthRequest.SerializeToString,
            jarvis__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jarvis.JarvisService/StreamEvents',
            jarvis__pb2.EventStreamRequest.SerializeToString,
            jarvis__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
